### ISSUE TITLE
Slim Variant

### ISSUE THREAD

**Issue by oscarmcm** [Swivelgames/apex-adapt-dark-ui#2]
Awesome work with this dark version, but have any plans for add [apex slim](https://github.com/apex/apex-ui-slim) support?

**Comment by Swivelgames** [comment]
@oscarmcm Absolutely! I'll be working on that next, as a few of my colleagues are asking for it as well!

I'll keep this issue updated with the progress.

**Comment by Swivelgames** [comment]
@oscarmcm Version one is available here: https://atom.io/themes/apex-adapt-dark-slim-ui

Let me know what you think!

I'll be adding things to it as I go. Throw some issues up in the `slim` repo if you want to see anything added to it :)

[Slim Variant Repo: https://github.com/Swivelgames/apex-adapt-dark-slim-ui/issues](https://github.com/Swivelgames/apex-adapt-dark-slim-ui/issues)

**Comment by oscarmcm** [comment]
@Swivelgames thanks for made it 

![image](https://user-images.githubusercontent.com/2553459/30005168-a7f1a62a-9099-11e7-87b8-8498196f827c.png)

There's a strange bug with color on number list, also i have 3 tabs opened and I cant see which is active.

Kudos!

**Comment by Swivelgames** [comment]
@oscarmcm Thanks man! Can you put these in new issues? One for the number list issue you're having, and another with the active tab issue? I'll see if I can push up some fixes today :)

**Comment by Swivelgames** [comment]
@oscarmcm Please review the following issue for active tab highlighting: https://github.com/Swivelgames/apex-adapt-dark-slim-ui/issues/2

As for the number list issue, can you [submit a new issue here](https://github.com/Swivelgames/apex-adapt-dark-slim-ui/issues/new) and go into some more detail? 👍
