### ISSUE TITLE
Feature Request: checkbox for enabling or disabling status-bar appear-on-hover

### ISSUE THREAD

**Issue by alanzanattadev** [Swivelgames/apex-adapt-dark-ui#4]
Hi,

It would be great to be able to disable somehow the fact that we have to hover the status-bar for it to appear. The status-bar is often used for diagnostics and others quick features, and it's a bit painful to use like this.

Btw, great job for the theme, beautiful !

Thank you.

**Comment by Swivelgames** [comment]
@alanzanattadev Great idea! I'll look into this.

**Comment by Swivelgames** [comment]
@alanzanattadev Done! Update to v0.4.0 and you'll see the option in `Settings` for `Auto-hide status bar`. Enjoy! 👍
